apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskapp
  template:
    metadata:
      labels:
        app: taskapp
    spec:
      containers:
      - name: taskapp
        image: taskapp:latest
        ports:
        - containerPort: 8080
